/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : bigint,
  'name' : string,
  'isNewArrival' : boolean,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'colors' : Array<string>,
  'price' : number,
  'isBestSeller' : boolean,
  'images' : Array<string>,
}
export interface Subscriber { 'email' : string, 'timestamp' : Time }
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      number,
      string,
      Array<string>,
      Array<string>,
      bigint,
      boolean,
      boolean,
    ],
    undefined
  >,
  'getAllProducts' : ActorMethod<
    [
      [] | [string],
      [] | [boolean],
      [] | [boolean],
      [] | [string],
      [] | [boolean],
    ],
    Array<Product>
  >,
  'getAllSubscribers' : ActorMethod<[], Array<Subscriber>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'submitReview' : ActorMethod<[bigint, string, bigint, string], undefined>,
  'subscribeEmail' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];